### ISSUE TITLE
better subtitles and shading, and stop forgetting caption settings

### ISSUE THREAD

**Issue by ToyKeeper** [Elias8477/YTQualityofLife#2]
YouTube's subtitles are ugly and it forgets the user's settings frequently.  So I made a CSS override to fix it.  I'm not sure if it's feasible to include in this extension, but if so, I attached the CSS override I made.

As a preview, here's how it looks on my screen:
![preview image](https://toykeeper.net/tmp/youtube-subtitles.jpg)

```css
/* YouTube, stop messing with my caption settings!
 * It seems to reset them to default at random, anywhere from
 * once every couple days to once every couple months...
 * so... I'll just override it */

div.caption-window, /* outer caption box */
span.captions-text, /* caption box area */
span.caption-visual-line, /* per line of text */
span.ytp-caption-segment, /* actual text */
foo {
    background: transparent !important;
    overflow: visible !important;
}

span.ytp-caption-segment { /* actual text */
    /* font-weight: bold; */
    font-size: 3.5em !important; /* similar to if youtube had a "125%" setting */
    font-family: "Quicksand Medium", Georgia, "Times New Roman", Times, "PT Serif Caption", serif !important;
    /* em, not px, so shadows will scale with the font size */
    text-shadow:
        #00000060 -0.05em  0      0.02em, /* outline */
        #00000060  0.05em  0      0.02em,
        #00000060  0      -0.05em 0.02em,
        #00000060  0       0.05em 0.02em,
        #00000060 -0.03em -0.03em 0.02em,
        #00000060 -0.03em  0.03em 0.02em,
        #00000060  0.03em -0.03em 0.02em,
        #00000080  0.05em 0.05em 0.10em, /* shadow */
        #000000c0  0.07em 0.10em 0.15em,
        #000000f0  0.10em 0.15em 0.25em !important;
    overflow: visible !important;
}

/* get rid of giant top+bottom shaded areas when paused */
.ytp-gradient-bottom, .ytp-gradient-top {
    background-image: none !important; */
}
.ytp-gradient-bottom {
    height: 6em !important;
    padding: 0 !important;
    /* sine curve to avoid Mach bands */
    background: linear-gradient(
        #00000000,
        #00000001,
        #00000003,
        #00000008,
        #0000000e,
        #00000015,
        #0000001d,
        #00000026,
        #00000030,
        #00000039,
        #00000042,
        #0000004a,
        #00000051,
        #00000057,
        #0000005c,
        #0000005f,
        #00000060
    ) !important;
}
.ytp-gradient-top {
    /* sine curve to avoid Mach bands */
    background: linear-gradient(
        #00000064,
        #0000005b,
        #00000051,
        #00000047,
        #0000003e,
        #00000035,
        #0000002d,
        #00000025,
        #0000001e,
        #00000017,
        #00000011,
        #0000000c,
        #00000008,
        #00000005,
        #00000002,
        #00000001,
        #00000000
    ) !important;
}
```
